language: android
jdk: oraclejdk8
cache: false
sudo: required
  
env:
    global:
        - ANDROID_BUILD_API_LEVEL=27
        - ANDROID_BUILD_TOOLS_VERSION=27.0.3

android:
    components:
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_BUILD_API_LEVEL
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository

notifications:
    email: true

git:
    submodules: false

script:
    - ./gradlew assembleDebug
    - ./gradlew test
